### ISSUE TITLE
reactive window can't move the camera

### ISSUE THREAD

**Issue by jinruozai** [ic3bug/Godot-3.2-Multiplayer-FPS#1]
Press esc exits the window, and then reactive window by left-click, unable to move the camera

**Comment by ic3bug** [comment]
You have to press ESC again to recapture the mouse, for now.
Adding the ability to recapture on mouse click.

**Comment by ic3bug** [comment]
Should fix the issue now.

**Comment by jinruozai** [comment]
It's too efficiency,great work!~
