### ISSUE TITLE
Server has lots of warnings

### ISSUE THREAD

**Issue by aaronfranke** [ic3bug/Godot-3.2-Multiplayer-FPS#2]
I was testing this for the asset library when I noticed that the server project has lots of warnings. These should probably be silenced. For example, prefix unused arguments with an underscore.

You may also wish to follow the [GDScript style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html).

By the way, nice project, I already approved it, I'm just giving feedback so you can make it even better.

**Comment by ic3bug** [comment]
Ok, thanks! Silencing those warnings.
