### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by drequivalent** [ic3bug/Godot-3.2-Multiplayer-FPS#4]
Grey screen after I press "play" - nothing happens.

**Comment by ic3bug** [comment]
Any errors in the output? Make sure to run the server first, then connect. If you play through the localhost specify it in the IP property of the main scene.

**Comment by NewNodeGames** [comment]
I get same error.

**Comment by drequivalent** [comment]
When I start both server and client on the same machine, the client says:

```
 Error listening on port 6007
```

**Comment by ic3bug** [comment]
Could be used by another program, try other ports.
Related: https://godotengine.org/qa/20139/error-listening-on-port-6007

It has nothing to do with the project so I'm closing the issue.
